In [13]:
import pandas as pd
df = pd.read_csv("../data/raw/zameen-property-data.csv")
df.head()

,property_id,location_id,page_url,property_type,price,location,city,province_name,latitude,longitude,baths,area,purpose,bedrooms,date_added,agency,agent
0,237062,3325,https://www.zameen.com/Property/g_10_g_10_2_gr...,Flat,10000000,G-10,Islamabad,Islamabad Capital,33.679890,73.012640,2,4 Marla,For Sale,2,02-04-2019,NaN,NaN
1,346905,3236,https://www.zameen.com/Property/e_11_2_service...,Flat,6900000,E-11,Islamabad,Islamabad Capital,33.700993,72.971492,3,5.6 Marla,For Sale,3,05-04-2019,NaN,NaN
2,386513,764,https://www.zameen.com/Property/islamabad_g_15...,House,16500000,G-15,Islamabad,Islamabad Capital,33.631486,72.926559,6,8 Marla,For Sale,5,07-17-2019,NaN,NaN
3,656161,340,https://www.zameen.com/Property/islamabad_bani...,House,43500000,Bani Gala,Islamabad,Islamabad Capital,33.707573,73.151199,4,2 Kanal,For Sale,4,04-05-2019,NaN,NaN
4,841645,3226,https://www.zameen.com/Property/dha_valley_dha...,House,7000000,DHA Defence,Islamabad,Islamabad Capital,33.492591,73.301339,3,8 Marla,For Sale,3,07-10-2019,Easy Property,Muhammad Junaid Ceo Muhammad Shahid Director

In [14]:
df.shape  #size of the dataset

(168446, 17)

In [15]:
df.columns.to_list() # columns list

['property_id',
 'location_id',
 'page_url',
 'property_type',
 'price',
 'location',
 'city',
 'province_name',
 'latitude',
 'longitude',
 'baths',
 'area',
 'purpose',
 'bedrooms',
 'date_added',
 'agency',
 'agent']

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 168446 entries, 0 to 168445
Data columns (total 17 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   property_id    168446 non-null  int64
 1   location_id    168446 non-null  int64
 2   page_url       168446 non-null  str
 3   property_type  168446 non-null  str
 4   price          168446 non-null  int64
 5   location       168446 non-null  str
 6   city           168446 non-null  str
 7   province_name  168446 non-null  str
 8   latitude       168446 non-null  float64
 9   longitude      168446 non-null  float64
 10  baths          168446 non-null  int64
 11  area           168446 non-null  str
 12  purpose        168446 non-null  str
 13  bedrooms       168446 non-null  int64
 14  date_added     168446 non-null  str
 15  agency         124375 non-null  str
 16  agent          124374 non-null  str
dtypes: float64(2), int64(5), str(10)
memory usage: 21.8 MB

In [17]:
df.isnull().sum() # checking missing values

property_id          0
location_id          0
page_url             0
property_type        0
price                0
location             0
city                 0
province_name        0
latitude             0
longitude            0
baths                0
area                 0
purpose              0
bedrooms             0
date_added           0
agency           44071
agent            44072
dtype: int64

In [18]:
df.duplicated().sum()  # checking Duplicated values

np.int64(0)

In [19]:
df[["agency","agent"]].head()

          agency                                         agent
0            NaN                                           NaN
1            NaN                                           NaN
2            NaN                                           NaN
3            NaN                                           NaN
4  Easy Property  Muhammad Junaid Ceo Muhammad Shahid Director

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 168446 entries, 0 to 168445
Data columns (total 17 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   property_id    168446 non-null  int64
 1   location_id    168446 non-null  int64
 2   page_url       168446 non-null  str
 3   property_type  168446 non-null  str
 4   price          168446 non-null  int64
 5   location       168446 non-null  str
 6   city           168446 non-null  str
 7   province_name  168446 non-null  str
 8   latitude       168446 non-null  float64
 9   longitude      168446 non-null  float64
 10  baths          168446 non-null  int64
 11  area           168446 non-null  str
 12  purpose        168446 non-null  str
 13  bedrooms       168446 non-null  int64
 14  date_added     168446 non-null  str
 15  agency         124375 non-null  str
 16  agent          124374 non-null  str
dtypes: float64(2), int64(5), str(10)
memory usage: 21.8 MB

In [22]:
drop_columns=[
    "property_id","location_id","page_url","agency","agent"
]
df = df.drop(columns=drop_columns)

In [23]:
df = df.drop_duplicates()

In [25]:
df.isnull().sum()

property_type    0
price            0
location         0
city             0
province_name    0
latitude         0
longitude        0
baths            0
area             0
purpose          0
bedrooms         0
date_added       0
dtype: int64

In [26]:
df["purpose"].value_counts()

purpose
For Sale    106352
For Rent     41605
Name: count, dtype: int64

In [27]:
df= df[df["purpose"]=="For Sale"]

In [28]:
df["property_type"] .value_counts()

property_type
House            78179
Flat             24117
Upper Portion     2228
Lower Portion      947
Farm House         572
Penthouse          284
Room                25
Name: count, dtype: int64

In [29]:
df.head(2)

,property_type,price,location,city,province_name,latitude,longitude,baths,area,purpose,bedrooms,date_added
0,Flat,10000000,G-10,Islamabad,Islamabad Capital,33.679890,73.012640,2,4 Marla,For Sale,2,02-04-2019
1,Flat,6900000,E-11,Islamabad,Islamabad Capital,33.700993,72.971492,3,5.6 Marla,For Sale,3,05-04-2019

In [33]:
df["area"].head(10)

0      4 Marla
1    5.6 Marla
2      8 Marla
3      2 Kanal
4      8 Marla
5    1.6 Kanal
6      1 Kanal
7    6.2 Marla
8      1 Kanal
9      1 Kanal
Name: area, dtype: str

In [ ]:
def convert_area_to_marla(value):
    value= str(value).strip()

    number = float(value.split()[0])
    unit = value.split()[1].lower()

    if unit == "marla":
        return number
    elif unit == "kanal":
        return number*20
    else:
        None

df["area_marla"] = df["area"].apply(convert_area_to_marla)

ValueError: could not convert string to float: '4,450'